# Generated by Django 6.0.6 on 2026-06-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                choices=[
                    ("IN", "Indian"),
                    ("CH", "Chinese"),
                    ("IT", "Italian"),
                    ("GR", "Greek"),
                    ("MX", "Mexican"),
                    ("FF", "Fastfood"),
                    ("OT", "Others"),
                ],
                default="",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
