# Generated by Django 6.0.6 on 2026-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                choices=[
                    ("BN", "Bangladeshi"),
                    ("IN", "Indian"),
                    ("CH", "Chinese"),
                    ("IT", "Italian"),
                    ("GR", "Greek"),
                    ("MX", "Mexican"),
                    ("FF", "Fastfood"),
                    ("OT", "Others"),
                ],
                max_length=2,
            ),
        ),
    ]
